import classNames from "classnames/bind";
import Tippy from "@tippyjs/react/headless";
import "tippy.js/dist/tippy.css";

import styles from "./VideoPage.module.scss";
import { SmileIcon } from "../../Layouts/Icons/Icons";

const cx = classNames.bind(styles);
function IconComment() {
  return (
    // Using a wrapper <div>  tag around the reference element solves this by creating a new parentNode context.
    <div>
      <Tippy
        hideOnClick={false}
        interactive
        delay={[100, 400]}
        placement="top-end"
        render={(attrs) => (
          <div className={cx("menu_list")} tabIndex="-1" {...attrs}>
            <ul className={cx("icon__list")}>
              <li
                data-index="0"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😀
              </li>
              <li
                data-index="1"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😃
              </li>
              <li
                data-index="2"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😄
              </li>
              <li
                data-index="3"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😁
              </li>
              <li
                data-index="4"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😆
              </li>
              <li
                data-index="5"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😅
              </li>
              <li
                data-index="6"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🤣
              </li>
              <li
                data-index="7"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😂
              </li>
              <li
                data-index="8"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🙂
              </li>
              <li
                data-index="9"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🙃
              </li>
              <li
                data-index="10"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😉
              </li>
              <li
                data-index="11"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😊
              </li>
              <li
                data-index="12"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😇
              </li>
              <li
                data-index="13"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😍
              </li>
              <li
                data-index="14"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😘
              </li>
              <li
                data-index="15"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😗
              </li>
              <li
                data-index="16"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😚
              </li>
              <li
                data-index="17"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😙
              </li>
              <li
                data-index="18"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😋
              </li>
              <li
                data-index="19"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😛
              </li>
              <li
                data-index="20"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😜
              </li>
              <li
                data-index="21"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😝
              </li>
              <li
                data-index="22"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🤑
              </li>
              <li
                data-index="23"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🤗
              </li>
              <li
                data-index="24"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🤔
              </li>
              <li
                data-index="25"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🤐
              </li>
              <li
                data-index="26"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😐
              </li>
              <li
                data-index="27"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😑
              </li>
              <li
                data-index="28"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😶
              </li>
              <li
                data-index="29"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😏
              </li>
              <li
                data-index="30"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😒
              </li>
              <li
                data-index="31"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🙄
              </li>
              <li
                data-index="32"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😬
              </li>
              <li
                data-index="33"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🤥
              </li>
              <li
                data-index="34"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😌
              </li>
              <li
                data-index="35"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😔
              </li>
              <li
                data-index="36"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😪
              </li>
              <li
                data-index="37"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🤤
              </li>
              <li
                data-index="38"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😴
              </li>
              <li
                data-index="39"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😷
              </li>
              <li
                data-index="40"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🤒
              </li>
              <li
                data-index="41"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🤕
              </li>
              <li
                data-index="42"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🤢
              </li>
              <li
                data-index="43"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🤧
              </li>
              <li
                data-index="44"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😵
              </li>
              <li
                data-index="45"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🤠
              </li>
              <li
                data-index="46"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😎
              </li>
              <li
                data-index="47"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🤓
              </li>
              <li
                data-index="48"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😕
              </li>
              <li
                data-index="49"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😟
              </li>
              <li
                data-index="50"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🙁
              </li>
              <li
                data-index="51"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😮
              </li>
              <li
                data-index="52"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😯
              </li>
              <li
                data-index="53"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😲
              </li>
              <li
                data-index="54"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😳
              </li>
              <li
                data-index="55"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😦
              </li>
              <li
                data-index="56"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😧
              </li>
              <li
                data-index="57"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😨
              </li>
              <li
                data-index="58"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😰
              </li>
              <li
                data-index="59"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😥
              </li>
              <li
                data-index="60"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😢
              </li>
              <li
                data-index="61"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😭
              </li>
              <li
                data-index="62"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😱
              </li>
              <li
                data-index="63"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😖
              </li>
              <li
                data-index="64"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😣
              </li>
              <li
                data-index="65"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😞
              </li>
              <li
                data-index="66"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😓
              </li>
              <li
                data-index="67"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😩
              </li>
              <li
                data-index="68"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😫
              </li>
              <li
                data-index="69"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😤
              </li>
              <li
                data-index="70"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😡
              </li>
              <li
                data-index="71"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😠
              </li>
              <li
                data-index="72"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😈
              </li>
              <li
                data-index="73"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                👿
              </li>
              <li
                data-index="74"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                💀
              </li>
              <li
                data-index="75"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                💩
              </li>
              <li
                data-index="76"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🤡
              </li>
              <li
                data-index="77"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                👹
              </li>
              <li
                data-index="78"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                👺
              </li>
              <li
                data-index="79"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                👻
              </li>
              <li
                data-index="80"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                👽
              </li>
              <li
                data-index="81"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                👾
              </li>
              <li
                data-index="82"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🤖
              </li>
              <li
                data-index="83"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😺
              </li>
              <li
                data-index="84"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😸
              </li>
              <li
                data-index="85"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😹
              </li>
              <li
                data-index="86"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😻
              </li>
              <li
                data-index="87"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😼
              </li>
              <li
                data-index="88"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😽
              </li>
              <li
                data-index="89"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                🙀
              </li>
              <li
                data-index="90"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😿
              </li>
              <li
                data-index="91"
                tabIndex="0"
                className={cx("icon__list__items")}
              >
                😾
              </li>
            </ul>
          </div>
        )}
      >
        <span>
          <SmileIcon />
        </span>
      </Tippy>
    </div>
  );
}

export default IconComment;
